# [Introduction to PyTorch](https://campus.datacamp.com/courses/introduction-to-deep-learning-with-pytorch/introduction-to-pytorch-a-deep-learning-library?ex=4)

DataCamp track learning.

## Import libraries

In [1]:
import torch

/home/devenv/Projects/deep-learning-with-pytorch/.venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


## 1 - Tensors

* Tensor: similar to array or matrix.
* Two tensors are compatilbe if they have the shame shape, exactly dimensions.

In [2]:
my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)

# Tensor attributes
print(tensor)
print(tensor.shape)
print(tensor.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [3]:
tensor_two = torch.tensor(
    [[7, 8, 9], [10, 11, 11]]
)
print(f'Tensor two dimentions: {tensor_two.shape}')

tensor_three = torch.tensor(
    [1, 2, 3]
)
print(f'Tensor three dimensions: {tensor_three.shape}')

Tensor two dimentions: torch.Size([2, 3])
Tensor three dimensions: torch.Size([3])


In [ ]:
# Tensor operations

print(tensor + tensor_two)
print(tensor / tensor_two)
print(tensor * tensor_two) # Elementwise multiplication

tensor_four = tensor @ tensor_three
print(tensor_four)
print(tensor_four.shape) # Matrix multiplication

tensor([[ 8, 10, 12],
        [14, 16, 17]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5455]])
tensor([[ 7, 16, 27],
        [40, 55, 66]])
tensor([14, 32])
torch.Size([2])


## 2 - Neural Networks and Layers

A neural network consists of input, hidden and output layers.

* Input layer: features in our dataset.
* Output layer: classes to predict.
* Hidden layers: layers between input and output layers.

In [17]:
# Fully connected network = Linear model

import torch.nn as nn

# Input tensor: 1 x 3, 3 features
input_tensor = torch.tensor(
    [[0.3471, 0.4547, -0.2356]]
)

# Linear layer: y0 = w0*X + b0
# w0 = weights
# X = features
# b0 = bias
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)

# Pass input tensor through liner layer
output = linear_layer(input_tensor)
print(output)

# Each linear layer has a set of weights and biases:
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[0.2701, 0.4470]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.2134, -0.0175,  0.4212],
        [ 0.2784,  0.5042, -0.1166]], requires_grad=True)
Parameter containing:
tensor([0.4513, 0.0936], requires_grad=True)


What is the role of weights in a neural network?

Weights determine how much influence each input has on the neurons's output.

### 2.1 - Hidden Layer and Parameters

Add hidden linear layers to the original model.

In [16]:
n_features = 3 # inputs
n_classes = 2 # outputs

model = nn.Sequential(
    nn.Linear(n_features, 8),
    nn.Linear(8, 4),
    nn.Linear(4, n_classes)
)

* Fully connected when each neuron links to all neuron in the previous layer.

* A neuron in a linear layer:
    - Perform a linear operation using all neurons from the previous layers.
    - Has n + 1 parameters: n from inputs and 1 for the bias.

* More hidden layers = more paramenters = higher model capacity or number of parameters in the model.

* Model capacity from avobe example:
    - Hidden layer one: 3 inputs, 8 neurons then 8 * (3 + 1) =  32
    - Hidden layer two: 8 inptus, 4 neurons then 4 * (8 + 1) = 36
    - Output layer: 4 inputs, 2 neurons then 2 * (4 + 1) = 10
    - Total parameters: 32 + 36 + 10 = 78

In [15]:
total = 0
for parameter in model.parameters():
    total += parameter.numel()
print(f'Model capacity = {total}')

Model capacity = 78


Balancing complexity and efficiency

Too many parameters can leadd to long training times or overfitting, while too few might limit learning capacity.

In [18]:
output = model(input_tensor)
print(output)

tensor([[-0.2304, -0.0628]], grad_fn=<AddmmBackward0>)
